apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeebe-gopro.fullname" . }}
  labels:
{{ include "zeebe-gopro.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "zeebe-gopro.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
